title: "Nami Kim"
description: "Data Engineer | AI ML Explorer"
theme: jekyll-theme-minimal
markdown: kramdown
plugins:
  - jekyll-feed
logo: /assets/me.jpg
show_downloads: false

# Manual language links
defaults:
  -
    scope:
      path: ""
    values:
      lang: "en"

# Optional: navbar language switch
header_pages:
  - index.md
  - index.ko.md