title: "Nami Kim"
description: "Data Engineer 🧡 AI ML"
baseurl: ""
url: ""
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Theme settings
logo: /assets/me.jpg
background_color: "#fcfbf8"
text_color: "#1c180d"
accent_color: "#9e8747"

# Social links
github_username: 
linkedin_username: 
location: "Korea"

# Build settings
exclude:
  - README.md
  - .gitignore
  - Gemfile
  - Gemfile.lock

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:path/

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
      lang: "en"
  - scope:
      path: "_projects"
    values:
      layout: "project"

# Manual language links
defaults:
  -
    scope:
      path: ""
    values:
      lang: "en"

# Optional: navbar language switch
header_pages:
  - index.md
  - index.ko.md